# to be manually updated
last_checkpoint = 32
checkpoint = false
upload = false

seed = 69
epochs = 1
batch_size = 512
learning_rate = 6e-3
b1 = 0.9
b2 = 0.999
weight_decay  = 3e-3
eval = false
vocab_size = 32
ctx_len = 77

layers = 6
use_bias = false
num_heads = 6
base_f = 5_000
embed_dim = 384
num_classes = 1944

ffn_dim = 384

proj_dim = 64
# 4x embed dim, recommended in simclr
proj_head_dim = 768
