_wandb:
    value:
        cli_version: 0.21.3
        e:
            lhceraaam2qpxte8q1m91ydf4ygv9ktt:
                codePath: main_ebm.py
                codePathLocal: main_ebm.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "499963174912"
                        used: "453891088384"
                email: apurva.jpr@gmail.com
                executable: /Users/apurva/projects/jax-models/chess/.venv/bin/python3
                host: Apurva-MacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-15.5-x86_64-i386-64bit
                program: /Users/apurva/projects/jax-models/chess/main_ebm.py
                python: CPython 3.11.10
                root: /Users/apurva/projects/jax-models/chess
                startedAt: "2025-09-04T00:59:17.235740Z"
                writerId: lhceraaam2qpxte8q1m91ydf4ygv9ktt
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 12
                - 45
                - 49
                - 53
                - 105
            "2":
                - 12
                - 45
                - 49
                - 53
                - 105
            "3":
                - 15
                - 16
            "4": 3.11.10
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-x86_64
alpha:
    value: 0.05
b1:
    value: 0.9
b2:
    value: 0.999
base_f:
    value: 5000
batch_size:
    value: 32
checkpoint:
    value: false
ctx_len:
    value: 77
embed_dim:
    value: 384
epochs:
    value: 1
eval:
    value: false
ffn_dim:
    value: 384
last_checkpoint:
    value: false
layers:
    value: 6
learning_rate:
    value: 0.006
min_lr_scale:
    value: 10
num_classes:
    value: 1944
num_heads:
    value: 6
proj_dim:
    value: 64
proj_head_dim:
    value: 768
seed:
    value: 69
sigma:
    value: 0.01
steps:
    value: 4
total_steps:
    value: 640
upload:
    value: false
use_bias:
    value: false
vocab_size:
    value: 32
warmup_steps:
    value: 10
weight_decay:
    value: 0.003
