seed = 69
epochs = 1
batch_size = 32
learning_rate = 0.003
weight_decay  = 0.03
eval = false

image_size = 32
patch_size = 8
layers = 12
use_bias = false
num_heads = 3
embed_dim = 192
channels = 3
num_classes = 10
labels = 10

ffn_dim = 768

diff_steps = 250
beta_1 = 0.001
beta_t = 0.02

